plant CRUD controller no service
succulentumz/succulentum-collection pull request #2
Opened 2024-10-15 15:40 UTC by EvgenVrp24

2024-10-15 15:47 UTC, EvgenVrp24 commented on demo/src/main/java/com/example/demo/api/dto/AckResponse.java
У Димы в старой реализации увидел, это дто чисто с булем, чтобы возвращать успех или нет

2024-10-15 15:48 UTC, EvgenVrp24 commented on demo/src/main/java/com/example/demo/api/dto/CreatePlantRequest.java
кк

2024-10-16 16:02 UTC, litvin12 requested changes

2024-10-16 16:06 UTC, EvgenVrp24 commented on demo/src/main/java/com/example/demo/api/dto/CreatePlantRequest.java
> +public class CreatePlantRequest {
Под @value класс и так final, но ок, эксплиситно укажу

2024-10-16 17:18 UTC, EvgenVrp24 commented on demo/src/main/java/com/example/demo/api/dto/CreatePlantRequest.java
> +    private Timestamp removedAt;
хз, на новой схеме просто timestamp, есть еще TimestampWithTimeZoneJdbcType, там есть пояса, можно его как вариант, но в дефолтном по идее поясов нет

2024-10-17 03:43 UTC, EvgenVrp24 commented on demo/src/main/java/com/example/demo/api/dto/CreatePlantRequest.java
> +    @NonNull
у ломбока с notempty валидацией тяжело, если в принципе возможно, поменял короче все на джакарту

2024-10-17 04:07 UTC, litvin12 approved these changes

2024-10-17 04:13 UTC, merged