Pagination, filtering, sorting
succulentumz/succulentum-collection pull request #8
Opened 2024-11-11 10:50 UTC by litvin12

2024-11-11 14:18 UTC, EvgenVrp24 approved these changes, later dismissed

2024-11-12 03:06 UTC, DmitryMustk requested changes

2024-11-12 03:49 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/plant/PlantService.java
> +    public void updatePlantPhoto(int id, UpdatePlantPhotoRequest request) {
Нет, но которую хотел нельзя закоментить она с прошлого pr

2024-11-12 07:13 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/plant/PlantController.java
> +    @PatchMapping("/{id}/photo")
звучит нормал, лайк

2024-11-12 21:06 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/plant/PlantController.java
> +    @PatchMapping("/{id}/photo")
>мне не нравится когда в контроллере есть вообще хоть какая-то логика

Ты про то, что в хедер ответа писать код ошибки? Так это не бизнес логика это как раз апи логика которой и есть место в контроллере

2024-11-15 23:03 UTC, DmitryMustk requested changes

2024-11-15 23:03 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/exception/ErrorMessage.java
> +    INVALID_INPUT("Неправильно введены данные в запросе");
Все подобные значения выноси в отдельный .properties файл (если вдруг займемся интернационализацией будет удобнее, да и эти сообщения могут еще где то юзатся (в тестах например) так что пускай они в одном месте лежат)

2024-11-22 03:07 UTC, DmitryMustk requested changes

2024-11-22 03:07 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/collection/CollectionService.java
>      }
Давай при апдейте и делите тоже проверять существует ли такой айдишник и кидать исключения

2024-11-22 03:07 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/collection/dto/CollectionFilter.java
> +    OffsetDateTime createdTo;
я мб не особо шарю, но почему тут поля как package-private объявлены?

2024-11-22 03:07 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/folder/FolderController.java
> +        return new ResponseEntity<>(folder, HttpStatus.CREATED);
Так же, отдавать uri

2024-11-22 03:07 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/plant/PlantController.java
> +        return new ResponseEntity<>(plant, HttpStatus.CREATED);
uri возвращать

2024-11-22 03:07 UTC, DmitryMustk commented on src/main/java/ru/succulentum/scollection/api/tag/TagController.java
> +    public ResponseEntity<TagResponse> createTag(@RequestBody @Valid CreateTagRequest request) {
uri

2025-02-17 13:44 UTC, EvgenVrp24 approved these changes

2025-02-18 02:53 UTC, DmitryMustk approved these changes

2025-02-18 02:53 UTC, merged